name: Deploy FastAPI to Compute Engine

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Compute Engine
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/test-compute-engine
            git pull origin main

            docker stop fastapi-app || true
            docker rm fastapi-app || true

            docker build -t fastapi-compute-engine .

            docker run -d \
              --name fastapi-app \
              --restart unless-stopped \
              -p 8000:8000 \
              fastapi-compute-engine